---
# This is the workflow for Deploying the software on Windows It should create an executable file
# The executable file should be uploaded as an artifact
# The executable file should be named "Fly Swapper 3000"
name: Deployment

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  linting:
    uses: ./.github/workflows/mega-linter.yaml
    permissions:
      contents: write
      issues: write
      pull-requests: write
      statuses: write
      
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Check if on main branch
        if: github.ref != 'refs/heads/main'
        run: |
          echo "This Tag is not on the main branch!"
          exit 1
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Verify Version
        run: |
            TAG_VERSION=${GITHUB_REF#refs/tags/v}
            TOML_VERSION=$(grep '^version =' pyproject.toml | sed -E 's/version = "([^"]+)"/\1/')
            if [ "$TAG_VERSION" != "$TOML_VERSION" ]; then
              echo "Version mismatch: tag is $TAG_VERSION but pyproject.toml is $TOML_VERSION"
              exit 1  # Exits with a non-zero status to fail the workflow
            fi
        shell: bash 
      - uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.12"
          spec: "main.py"
          requirements: "requirements.txt"
          upload_exe_with_name: "Fly Plotter 4000"
          options: --onefile, --name "Fly Plotter 4000", --icon ".\docs\\SG Logo.ico", --add-data ".\docs\;docs"
